//! Adapted from <https://github.com/YarnSpinnerTool/YarnSpinner/blob/3a5b7343f715e4e9a3705fa4224e7fa510b92f1c/YarnSpinner.Compiler/IndentAwareLexer.cs>
//!
//! The C# implementation uses inheritance to do this.
//! More specifically, the lexer generated by ANTLR derives from the `IndentAwareLexer`
//! directly, and the `IndentAwareLexer` derives from the ANTLR Lexer base class.
//! Instead of this, we use a proxy/wrapper around the generated lexer to handle everything correctly.

use super::enum_registry::{EnumCaseValue, EnumRegistry, format_enum_number};
use super::generated::yarnspinnerlexer::{self, LocalTokenFactory, YarnSpinnerLexer as GeneratedYarnSpinnerLexer};
use crate::collections::*;
use crate::file_parse_result::LineGroupMetadata;
use crate::listeners::{Diagnostic, DiagnosticDescriptor};
use crate::prelude::{DiagnosticSeverity, TokenExt, create_common_token};
use antlr4rust::char_stream::CharStream;
use antlr4rust::token::{CommonToken, TOKEN_DEFAULT_CHANNEL, Token};
use antlr4rust::token_factory::{CommonTokenFactory, TokenFactory};
use antlr4rust::{Lexer, TokenSource};
use std::cell::RefCell;
use std::ops::{Deref, DerefMut, Range};
use std::rc::Rc;
use yarnspinner_core::prelude::*;

// To ensure we don't accidentally use the wrong lexer, this will produce errors on use.
#[allow(dead_code)]
type YarnSpinnerLexer = ();

antlr4rust::tid! { impl<'input, Input> TidAble<'input> for IndentAwareYarnSpinnerLexer<'input, Input> where Input:CharStream<From<'input>> }

/// A Lexer subclass that detects newlines and generates indent and dedent tokens accordingly.
///
/// ## Implementation notes
///
/// In contrast to the original implementation, the warnings emitted by this lexer are actually respected in the diagnostics.
pub(crate) struct IndentAwareYarnSpinnerLexer<'input, Input: CharStream<From<'input>>, TF: TokenFactory<'input> = LocalTokenFactory<'input>> {
    base: GeneratedYarnSpinnerLexer<'input, Input>,
    hit_eof: bool,
    /// Holds the last observed token from the stream.
    /// Used to see if a line is blank or not.
    last_token: Option<TF::Tok>,
    /// The collection of tokens that we have seen, but have not yet
    /// returned. This is needed when NextToken encounters a newline,
    /// which means we need to buffer indents or dedents. [`next_token`]
    /// only returns a single [`Token`] at a time, which
    /// means we use this list to buffer it.
    pending_tokens: Queue<TF::Tok>,
    /// A flag to say the last line observed was a shortcut or not.
    /// Used to determine if tracking indents needs to occur.
    line_contains_shortcut: bool,
    /// Keeps track of the last indentation encountered.
    /// This is used to see if depth has changed between lines.
    last_indent: isize,
    /// A stack keeping track of the levels of indentations we have seen so far that are relevant to shortcuts.
    unbalanced_indents: Stack<isize>,
    /// holds the line number of the last seen option.
    /// Lets us work out if the blank line needs to end the option.
    last_seen_option_content: Option<isize>,
    file_name: String,
    pub(crate) diagnostics: Rc<RefCell<Vec<Diagnostic>>>,
    /// Lookahead token buffered by `maybe_coalesce_keyword_prefix` when the
    /// keyword was NOT a prefix of a longer identifier.
    peeked_base_token: Option<TF::Tok>,
    /// Tracks how many `<<if>>` blocks with DOT-notation in their condition
    /// have been coalesced into COMMAND_TEXT rather than parsed as real
    /// if_statements.  Used to also coalesce the matching `<<else>>` /
    /// `<<elseif>>` / `<<endif>>` tokens.
    dot_if_nesting_depth: usize,
    /// Extra tokens to emit AFTER the current token produced by
    /// `check_next_token`.  Set by `maybe_coalesce_keyword_prefix` when a
    /// COMMAND_IF with no DOT is encountered and its expression tokens were
    /// consumed by the look-ahead scan but must be re-emitted.
    deferred_tokens: Vec<TF::Tok>,
    /// Registry of enum types built from a pre-scan of the source text.
    /// Used by `maybe_merge_member_access` and the COMMAND_IF handler to
    /// resolve `EnumType.Member` and `.Member` references into their raw
    /// numeric or string values.
    pub(crate) enum_registry: EnumRegistry,
    /// Shared metadata about `=>` line group arrows detected during lexing.
    /// Read after parsing to pass to the code generation visitor.
    pub(crate) line_group_metadata: Rc<RefCell<LineGroupMetadata>>,
    /// Whether we are currently inside a `<<once>>` block.
    in_once_block: bool,
    /// Whether the current once block is a `<<once if expr>>` (needs two endifs).
    once_if_block: bool,
    /// Whether the COMMAND_TEXT_END following a suppressed once/endonce
    /// command should also be suppressed.
    suppress_next_command_text_end: bool,
    /// Whether text (TEXT or SHORTCUT_ARROW) has been seen on the current
    /// line before a `<<once>>` command. Used to distinguish block-level
    /// once (at line start) from line-level once (after text).
    has_text_on_current_line: bool,
    /// The full source text of the file being lexed.
    /// Used to compute line/column positions for diagnostics.
    pub(crate) source: String,
}

impl<'input, Input: CharStream<From<'input>>> Deref for IndentAwareYarnSpinnerLexer<'input, Input> {
    type Target = GeneratedYarnSpinnerLexer<'input, Input>;

    fn deref(&self) -> &Self::Target {
        &self.base
    }
}

impl<'input, Input: CharStream<From<'input>>> DerefMut for IndentAwareYarnSpinnerLexer<'input, Input> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.base
    }
}

impl<'input, Input: CharStream<From<'input>>> TokenSource<'input> for IndentAwareYarnSpinnerLexer<'input, Input> {
    type TF = LocalTokenFactory<'input>;

    fn next_token(&mut self) -> <Self::TF as TokenFactory<'input>>::Tok {
        if self.hit_eof && !self.pending_tokens.0.is_empty() {
            // We have hit the EOF, but we have tokens still pending.
            // Start returning those tokens.
            self.pending_tokens.dequeue().unwrap()
        } else if self.base.input().size() == 0 {
            self.hit_eof = true;
            create_common_token(antlr4rust::token::TOKEN_EOF, "<EOF>")
        } else {
            // Get the next token, which will enqueue one or more new
            // tokens into the pending tokens queue.
            self.check_next_token();

            // `check_next_token` will always set at least one pending token if `self.base.input().size() > 0`
            // if `self.base.input().size() == 0`, the branch returning the EOF token is already entered ahead of this.
            self.pending_tokens.dequeue().unwrap()
        }
    }

    fn get_input_stream(&mut self) -> Option<&mut dyn antlr4rust::int_stream::IntStream> {
        self.base.get_input_stream()
    }

    fn get_source_name(&self) -> String {
        self.base.get_source_name()
    }

    fn get_token_factory(&self) -> &'input Self::TF {
        self.base.get_token_factory()
    }
    fn get_dfa_string(&self) -> String {
        self.base.get_dfa_string()
    }
}

/// Copied from generated/yarnspinnerlexer.rs
type From<'a> = <LocalTokenFactory<'a> as TokenFactory<'a>>::From;

impl<'input, Input: CharStream<From<'input>>> IndentAwareYarnSpinnerLexer<'input, Input>
where
    &'input LocalTokenFactory<'input>: Default,
{
    pub fn new(input: Input, file_name: String) -> Self {
        IndentAwareYarnSpinnerLexer {
            file_name,
            base: GeneratedYarnSpinnerLexer::new(input),
            hit_eof: false,
            last_token: Default::default(),
            pending_tokens: Default::default(),
            line_contains_shortcut: false,
            last_indent: Default::default(),
            unbalanced_indents: Default::default(),
            last_seen_option_content: None,
            diagnostics: Default::default(),
            peeked_base_token: None,
            dot_if_nesting_depth: 0,
            deferred_tokens: Vec::new(),
            enum_registry: EnumRegistry::default(),
            line_group_metadata: Rc::new(RefCell::new(LineGroupMetadata::default())),
            in_once_block: false,
            once_if_block: false,
            suppress_next_command_text_end: false,
            has_text_on_current_line: false,
            source: String::new(),
        }
    }

    /// If a command keyword token (e.g. `COMMAND_IF`) is immediately followed
    /// by an alphanumeric character with no whitespace gap, the v2.5 ANTLR lexer
    /// (which lacks the `IsEndOfCommandKeyword()` semantic predicate added in v3.0)
    /// will mis-tokenise `<<iffy>>` as COMMAND_IF + "fy".  This method detects that
    /// situation and merges the keyword together with the trailing identifier fragment
    /// into a single COMMAND_TEXT token, matching the v3.0 behaviour.
    fn maybe_coalesce_keyword_prefix(&mut self, token: Box<CommonToken<'input>>) -> Box<CommonToken<'input>> {
        if !matches!(
            token.token_type,
            yarnspinnerlexer::COMMAND_IF
                | yarnspinnerlexer::COMMAND_ELSEIF
                | yarnspinnerlexer::COMMAND_ELSE
                | yarnspinnerlexer::COMMAND_SET
                | yarnspinnerlexer::COMMAND_ENDIF
                | yarnspinnerlexer::COMMAND_CALL
                | yarnspinnerlexer::COMMAND_DECLARE
                | yarnspinnerlexer::COMMAND_JUMP
                | yarnspinnerlexer::COMMAND_ENUM
                | yarnspinnerlexer::COMMAND_CASE
                | yarnspinnerlexer::COMMAND_ENDENUM
                | yarnspinnerlexer::COMMAND_LOCAL
        ) {
            return token;
        }

        let keyword_stop = token.stop;

        // Consume the next token (already lexed in whatever mode keyword pushed).
        let next = self.base.next_token();

        // A word-like token that starts immediately after the keyword (no gap)
        // indicates the keyword was only a prefix of a longer identifier.
        let is_word = |tt: i32| matches!(tt, yarnspinnerlexer::COMMAND_TEXT | yarnspinnerlexer::FUNC_ID | yarnspinnerlexer::ID);

        // A token type that terminates coalescing (end-of-command or line).
        let is_terminator = |tt: i32| {
            matches!(
                tt,
                yarnspinnerlexer::COMMAND_END | yarnspinnerlexer::COMMAND_NEWLINE | yarnspinnerlexer::NEWLINE | yarnspinnerlexer::BODY_END
            ) || tt == antlr4rust::token::TOKEN_EOF
        };

        if is_word(next.token_type)
            && next.start == keyword_stop + 1
            && next.channel == TOKEN_DEFAULT_CHANNEL
            && !matches!(
                token.token_type,
                yarnspinnerlexer::COMMAND_IF
                    | yarnspinnerlexer::COMMAND_ELSEIF
                    | yarnspinnerlexer::COMMAND_CALL
                    | yarnspinnerlexer::COMMAND_SET
                    | yarnspinnerlexer::COMMAND_DECLARE
                    | yarnspinnerlexer::COMMAND_JUMP
            )
        {
            // Build the merged text.
            let mut combined = token.get_text().to_owned();
            combined.push_str(next.get_text());
            let mut last_stop = next.stop;
            // Track whether a DOT appeared in the expression of a COMMAND_IF
            // (enum member access like `EnumA.One`).  When detected, the resulting
            // COMMAND_TEXT is not a valid v2.5 if_statement, so we record the
            // nesting depth so that `<<else>>` / `<<endif>>` can also be coalesced.
            let mut found_dot_in_if_expr = false;

            // Consume any further adjacent tokens on the default channel until a
            // terminator is reached.  This absorbs the full argument list of
            // commands like `<<call func(args)>>` and `<<case One = "value">>` so
            // the parser sees a single COMMAND_TEXT token rather than hitting
            // unexpected-token errors on '(', '=' etc.
            loop {
                let cont = self.base.next_token();
                if !is_terminator(cont.token_type) && cont.channel == TOKEN_DEFAULT_CHANNEL && cont.start == last_stop + 1 {
                    if token.token_type == yarnspinnerlexer::COMMAND_IF && cont.token_type == yarnspinnerlexer::DOT {
                        found_dot_in_if_expr = true;
                    }
                    combined.push_str(cont.get_text());
                    last_stop = cont.stop;
                } else {
                    // Keywords that push ExpressionMode (e.g. COMMAND_IF) produce
                    // COMMAND_END (76) for `>>` via EXPRESSION_COMMAND_END.  The
                    // parser expects COMMAND_TEXT_END (78) to close a text command
                    // body, so retype it here.  The mode cleanup (double-pop) has
                    // already been applied by the base lexer internally.
                    let mut break_tok = cont;
                    // For v3.0 enum keywords (COMMAND_CASE/ENUM/ENDENUM/LOCAL),
                    // the identifier may be followed by hidden-channel tokens and
                    // further expression tokens (e.g. `<<case Name = value>>`).
                    // If the breaking token is not already a terminator, drain the
                    // remaining tokens until COMMAND_END so they don't leak into
                    // the parser stream as unexpected tokens.
                    if !is_terminator(break_tok.token_type)
                        && matches!(
                            token.token_type,
                            yarnspinnerlexer::COMMAND_CASE
                                | yarnspinnerlexer::COMMAND_ENUM
                                | yarnspinnerlexer::COMMAND_ENDENUM
                                | yarnspinnerlexer::COMMAND_LOCAL
                        )
                    {
                        while !is_terminator(break_tok.token_type) {
                            break_tok = self.base.next_token();
                        }
                    }
                    if break_tok.token_type == yarnspinnerlexer::COMMAND_END {
                        break_tok.token_type = yarnspinnerlexer::COMMAND_TEXT_END;
                    }
                    self.peeked_base_token = Some(break_tok);
                    break;
                }
            }

            // If this was a COMMAND_IF with enum dot-notation, record it so that
            // the matching <<else>> / <<endif>> tokens are also coalesced.
            if found_dot_in_if_expr {
                self.dot_if_nesting_depth += 1;
            }

            // Produce a single COMMAND_TEXT token spanning the whole identifier.
            let mut merged = (*token).clone();
            merged.token_type = yarnspinnerlexer::COMMAND_TEXT;
            merged.text = combined.into();
            merged.stop = last_stop;
            Box::new(merged)
        } else {
            // Not a prefix — return the keyword unchanged or coalesce it.

            if matches!(
                token.token_type,
                yarnspinnerlexer::COMMAND_ENDENUM | yarnspinnerlexer::COMMAND_ENUM | yarnspinnerlexer::COMMAND_CASE | yarnspinnerlexer::COMMAND_LOCAL
            ) {
                // v3.0 keywords with no grammar rule: consume all tokens until
                // COMMAND_END, then emit COMMAND_TEXT + peeked COMMAND_TEXT_END.
                // This handles `<<case Name = value>>` where trailing tokens after
                // the identifier would otherwise leak into the parser stream.
                let mut sink = next;
                while sink.token_type != yarnspinnerlexer::COMMAND_END
                    && sink.token_type != yarnspinnerlexer::COMMAND_NEWLINE
                    && sink.token_type != antlr4rust::token::TOKEN_EOF
                {
                    sink = self.base.next_token();
                }
                sink.token_type = yarnspinnerlexer::COMMAND_TEXT_END;
                self.peeked_base_token = Some(sink);
                let mut t = (*token).clone();
                t.token_type = yarnspinnerlexer::COMMAND_TEXT;
                Box::new(t)
            } else if token.token_type == yarnspinnerlexer::COMMAND_IF {
                // v3.0 `<<if expr>>` where the expression may contain enum member
                // access (`EnumType.Member` or shorthand `.Member`).
                // We always defer the expression tokens so the parser sees a
                // genuine `if_statement`, then resolve any enum members inline.
                let mut collected: Vec<Box<CommonToken<'input>>> = vec![next];
                let mut has_dot = false;
                loop {
                    let tok = self.base.next_token();
                    let tt = tok.token_type;
                    if tt == yarnspinnerlexer::DOT {
                        has_dot = true;
                    }
                    let is_end = tt == yarnspinnerlexer::COMMAND_END || tt == yarnspinnerlexer::COMMAND_NEWLINE || tt == antlr4rust::token::TOKEN_EOF;
                    collected.push(tok);
                    if is_end {
                        break;
                    }
                }

                if has_dot {
                    // Resolve enum members inline and detect cross-type comparisons.
                    let mut enum_types_seen = std::collections::HashSet::new();
                    let mut resolved: Vec<Box<CommonToken<'input>>> = Vec::with_capacity(collected.len());
                    let mut i = 0;
                    while i < collected.len() {
                        // FUNC_ID DOT FUNC_ID → EnumType.Member
                        if i + 2 < collected.len()
                            && (collected[i].token_type == yarnspinnerlexer::FUNC_ID || collected[i].token_type == yarnspinnerlexer::ID)
                            && collected[i + 1].token_type == yarnspinnerlexer::DOT
                            && collected[i + 1].start == collected[i].stop + 1
                            && (collected[i + 2].token_type == yarnspinnerlexer::FUNC_ID || collected[i + 2].token_type == yarnspinnerlexer::ID)
                            && collected[i + 2].start == collected[i + 1].stop + 1
                        {
                            let type_name = collected[i].get_text().to_owned();
                            let member_name = collected[i + 2].get_text().to_owned();
                            if let Some(val) = self.enum_registry.lookup(&type_name, &member_name) {
                                enum_types_seen.insert(type_name);
                                let mut merged = (*collected[i]).clone();
                                match val {
                                    EnumCaseValue::Number(n) => {
                                        merged.token_type = yarnspinnerlexer::NUMBER;
                                        merged.text = format_enum_number(*n).into();
                                    }
                                    EnumCaseValue::Str(s) => {
                                        merged.token_type = yarnspinnerlexer::STRING;
                                        merged.text = format!("\"{}\"", s).into();
                                    }
                                }
                                merged.stop = collected[i + 2].stop;
                                resolved.push(Box::new(merged));
                                i += 3;
                                continue;
                            }
                        }
                        // DOT FUNC_ID → shorthand .Member
                        if i + 1 < collected.len()
                            && collected[i].token_type == yarnspinnerlexer::DOT
                            && (collected[i + 1].token_type == yarnspinnerlexer::FUNC_ID || collected[i + 1].token_type == yarnspinnerlexer::ID)
                            && collected[i + 1].start == collected[i].stop + 1
                        {
                            let member_name = collected[i + 1].get_text().to_owned();
                            if let Some(val) = self.enum_registry.lookup_member_unique(&member_name) {
                                let mut merged = (*collected[i]).clone();
                                match val {
                                    EnumCaseValue::Number(n) => {
                                        merged.token_type = yarnspinnerlexer::NUMBER;
                                        merged.text = format_enum_number(*n).into();
                                    }
                                    EnumCaseValue::Str(s) => {
                                        merged.token_type = yarnspinnerlexer::STRING;
                                        merged.text = format!("\"{}\"", s).into();
                                    }
                                }
                                merged.stop = collected[i + 1].stop;
                                resolved.push(Box::new(merged));
                                i += 2;
                                continue;
                            }
                        }
                        resolved.push(collected[i].clone());
                        i += 1;
                    }
                    if enum_types_seen.len() > 1 {
                        self.diagnostics
                            .borrow_mut()
                            .push(Diagnostic::from_message("Cannot compare values from different enum types").with_file_name(&self.file_name));
                    }
                    self.deferred_tokens = resolved;
                } else {
                    // No DOT: return COMMAND_IF and defer the expression tokens.
                    self.deferred_tokens = collected;
                }
                token
            } else if (token.token_type == yarnspinnerlexer::COMMAND_ENDIF
                || token.token_type == yarnspinnerlexer::COMMAND_ELSE
                || token.token_type == yarnspinnerlexer::COMMAND_ELSEIF)
                && self.dot_if_nesting_depth > 0
            {
                // Close or continue a coalesced DOT-if block.
                // Close or continue a coalesced DOT-if block.
                if token.token_type == yarnspinnerlexer::COMMAND_ENDIF {
                    self.dot_if_nesting_depth -= 1;
                }
                let mut next_peeked = next;
                if next_peeked.token_type == yarnspinnerlexer::COMMAND_END {
                    next_peeked.token_type = yarnspinnerlexer::COMMAND_TEXT_END;
                }
                self.peeked_base_token = Some(next_peeked);
                let mut t = (*token).clone();
                t.token_type = yarnspinnerlexer::COMMAND_TEXT;
                Box::new(t)
            } else {
                self.peeked_base_token = Some(next);
                token
            }
        }
    }

    /// Detects the pattern `FUNC_ID DOT (FUNC_ID|ID)` (v3.0 enum member access
    /// like `EnumA.One`) and merges it into a single `STRING` token so that the
    /// v2.5 expression grammar — which has no dot-notation rule — can accept it
    /// as a valid expression value.
    ///
    /// If the pattern doesn't fully match, the original token is returned
    /// unchanged and any lookahead tokens are saved for the next call.
    fn maybe_merge_member_access(&mut self, token: Box<CommonToken<'input>>) -> Box<CommonToken<'input>> {
        // Handle standalone `.Member` shorthand: resolve against the registry.
        if token.token_type == yarnspinnerlexer::DOT {
            let next = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());
            if (next.token_type == yarnspinnerlexer::FUNC_ID || next.token_type == yarnspinnerlexer::ID) && next.start == token.stop + 1 {
                let member_name = next.get_text().to_owned();
                if let Some(val) = self.enum_registry.lookup_member_unique(&member_name) {
                    let mut merged = (*token).clone();
                    match val {
                        EnumCaseValue::Number(n) => {
                            merged.token_type = yarnspinnerlexer::NUMBER;
                            merged.text = format_enum_number(*n).into();
                        }
                        EnumCaseValue::Str(s) => {
                            merged.token_type = yarnspinnerlexer::STRING;
                            merged.text = format!("\"{}\"", s).into();
                        }
                    }
                    merged.stop = next.stop;
                    return Box::new(merged);
                }
            }
            // Not resolvable — put back and return DOT unchanged.
            self.peeked_base_token = Some(next);
            return token;
        }

        if token.token_type != yarnspinnerlexer::FUNC_ID && token.token_type != yarnspinnerlexer::ID {
            return token;
        }

        // Peek at the very next token (from the peeked slot or the base lexer).
        let next = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());

        if next.token_type == yarnspinnerlexer::DOT && next.start == token.stop + 1 {
            // Immediately-adjacent DOT — looks like enum member access.
            let after_dot = self.base.next_token();
            if (after_dot.token_type == yarnspinnerlexer::FUNC_ID || after_dot.token_type == yarnspinnerlexer::ID) && after_dot.start == next.stop + 1
            {
                // Try the enum registry first.
                let type_name = token.get_text();
                let member_name = after_dot.get_text();
                if let Some(val) = self.enum_registry.lookup(type_name, member_name) {
                    let mut merged = (*token).clone();
                    match val {
                        EnumCaseValue::Number(n) => {
                            merged.token_type = yarnspinnerlexer::NUMBER;
                            merged.text = format_enum_number(*n).into();
                        }
                        EnumCaseValue::Str(s) => {
                            merged.token_type = yarnspinnerlexer::STRING;
                            merged.text = format!("\"{}\"", s).into();
                        }
                    }
                    merged.stop = after_dot.stop;
                    return Box::new(merged);
                }

                // If `type_name` is a known enum but `member_name` is not a valid
                // case, emit an InvalidMemberAccess diagnostic (YS0038).
                if self.enum_registry.is_enum_type(type_name) {
                    let start_pos = char_offset_to_position(&self.source, token.start as usize);
                    let end_pos = char_offset_to_position(&self.source, after_dot.stop as usize + 1);
                    self.diagnostics
                        .borrow_mut()
                        .push(DiagnosticDescriptor::INVALID_MEMBER_ACCESS.create_with_range(
                            &self.file_name,
                            start_pos..end_pos,
                            format!("{type_name} doesn't have a member named {member_name}"),
                        ));
                }

                // Fall back: merge into a STRING literal so the expression grammar
                // accepts it (original v2.5 behaviour for unknown member access).
                let combined = format!("{}.{}", token.get_text(), after_dot.get_text());
                let mut merged = (*token).clone();
                merged.token_type = yarnspinnerlexer::STRING;
                merged.text = format!("\"{}\"", combined).into();
                merged.stop = after_dot.stop;
                // peeked_base_token is now empty; further tokens come from base.
                return Box::new(merged);
            }
            // DOT not followed by an identifier: emit the original token and DOT
            // in the correct order, then carry `after_dot` as the peeked token.
            // We do this by enqueueing the original token directly so that it
            // precedes the DOT which will be enqueued by the match arm below.
            self.pending_tokens.enqueue(token);
            self.peeked_base_token = Some(after_dot);
            return next; // DOT becomes the "current" token processed by the match arm.
        }

        // Not a DOT (or not adjacent): restore the peeked slot and return unchanged.
        self.peeked_base_token = Some(next);
        token
    }

    /// Detects the v3.0 line group arrow `=>` and converts it to a
    /// SHORTCUT_ARROW (`->`) token. In the v2.5 lexer, `=>` at the start
    /// of a body line produces TEXT("=") followed by TEXT("> ..."). We
    /// detect this pattern and emit SHORTCUT_ARROW instead, stripping the
    /// leading `> ` from the subsequent TEXT token. The arrow's position is
    /// recorded in `line_group_metadata` so the code gen visitor can emit
    /// saliency instructions instead of option instructions.
    fn maybe_convert_line_group_arrow(&mut self, token: Box<CommonToken<'input>>) -> Box<CommonToken<'input>> {
        // Only consider TEXT tokens with content "="
        if token.token_type != yarnspinnerlexer::TEXT || token.get_text() != "=" {
            return token;
        }

        // Peek at the next token
        let next = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());

        // Check: next must be TEXT, start with ">", and be immediately adjacent
        if next.token_type == yarnspinnerlexer::TEXT && next.get_text().starts_with('>') && next.start == token.stop + 1 {
            // This is a line group arrow (=>).
            // Create a SHORTCUT_ARROW token spanning both characters.
            let arrow_start = token.start;
            let mut arrow = (*token).clone();
            arrow.token_type = yarnspinnerlexer::SHORTCUT_ARROW;
            arrow.text = "=>".into();
            arrow.stop = token.stop + 1; // include the '>'

            // Record this arrow in the line group metadata.
            self.line_group_metadata.borrow_mut().converted_arrows.insert(arrow_start);
            if self.in_once_block {
                self.line_group_metadata.borrow_mut().once_arrows.insert(arrow_start);
            }

            // Strip the leading "> " (or just ">") from the next TEXT token.
            let text = next.get_text();
            let remaining = if let Some(stripped) = text.strip_prefix("> ") {
                stripped
            } else {
                &text[1..] // just ">"
            };

            if !remaining.is_empty() {
                let skip = text.len() - remaining.len();
                let mut modified = (*next).clone();
                modified.text = remaining.to_owned().into();
                modified.start = next.start + skip as isize;
                self.peeked_base_token = Some(Box::new(modified));
            }
            // If remaining is empty, the next token is consumed entirely.

            return Box::new(arrow);
        }

        // Not a line group arrow — put back the peeked token.
        self.peeked_base_token = Some(next);
        token
    }

    /// Fixes `UNESCAPABLE_CHARACTER` tokens emitted by the base ANTLR lexer.
    ///
    /// The generated lexer's ATN has a `type(TEXT)` action on the
    /// `UNESCAPABLE_CHARACTER` rule, but the Rust runtime does not apply it,
    /// so these tokens arrive with type 21 instead of TEXT (20).  The parser
    /// grammar only references TEXT, causing parse errors.
    ///
    /// Additionally, the base lexer **skips** (rather than hides) the `\`
    /// token in TextMode (`TEXT_ESCAPE`), so the backslash is lost entirely.
    /// For `:`, we re-insert the backslash to produce TEXT `\:`, matching
    /// the v3.2.0 `ESCAPED_SPEAKER_START` / `TEXT_ESCAPED_SPEAKER` rules.
    /// The runtime `LineParser` later converts `\:` → `:`.
    fn maybe_fix_unescapable_character(&mut self, token: Box<CommonToken<'input>>) -> Box<CommonToken<'input>> {
        if token.token_type != yarnspinnerlexer::UNESCAPABLE_CHARACTER {
            return token;
        }

        let mut fixed = (*token).clone();
        fixed.token_type = yarnspinnerlexer::TEXT;

        // For `:`, prepend the `\` that was skipped by the base lexer so
        // the string table contains `\:` (needed by LineParser).
        if fixed.get_text() == ":" {
            fixed.text = "\\:".into();
            // Extend start backwards to include the skipped `\` character.
            fixed.start -= 1;
        }

        Box::new(fixed)
    }

    fn check_next_token(&mut self) {
        let current = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());
        let current = self.maybe_fix_unescapable_character(current);

        let current = self.maybe_coalesce_keyword_prefix(current);
        let current = self.maybe_merge_member_access(current);

        // Detect v3.0 line group arrow (=>) and convert to SHORTCUT_ARROW.
        // In the v2.5 lexer, `=>` at the start of a body line produces
        // TEXT("=") (from BodyMode ANY rule) followed by TEXT("> rest of line...")
        // (from TextMode). We detect this pattern and convert to SHORTCUT_ARROW.
        let current = self.maybe_convert_line_group_arrow(current);

        match current.token_type {
            // Insert indents or dedents depending on the next token's
            // indentation, and enqueues the newline at the correct place
            yarnspinnerlexer::NEWLINE => {
                self.has_text_on_current_line = false;
                self.handle_newline_token(current.clone());
            }
            // Insert dedents before the end of the file, and then
            // enqueues the EOF.
            antlr4rust::token::TOKEN_EOF => self.handle_eof_token(current.clone()),
            yarnspinnerlexer::SHORTCUT_ARROW => {
                self.has_text_on_current_line = true;
                self.pending_tokens.enqueue(current.clone());
                self.line_contains_shortcut = true;
            }
            // v3 lexer emits LINE_GROUP_ARROW (=>) directly as its own token type.
            // Record its position so check_preview_features can detect line groups.
            yarnspinnerlexer::LINE_GROUP_ARROW => {
                self.has_text_on_current_line = true;
                self.line_group_metadata.borrow_mut().converted_arrows.insert(current.start);
                if self.in_once_block {
                    self.line_group_metadata.borrow_mut().once_arrows.insert(current.start);
                }
                // Convert to SHORTCUT_ARROW so the parser's shortcut_option rule matches.
                let mut converted = (*current).clone();
                converted.token_type = yarnspinnerlexer::SHORTCUT_ARROW;
                self.pending_tokens.enqueue(Box::new(converted));
                self.line_contains_shortcut = true;
            }
            // Detect <<once>> / <<endonce>> at the COMMAND_START level.
            // Transform once/endonce into if/set/endif tokens so the v2.5
            // parser can handle them without a dedicated once_statement rule.
            yarnspinnerlexer::COMMAND_START => {
                // Peek ahead and accumulate all consecutive COMMAND_TEXT tokens
                // to get the full command text. In the v2.5 lexer, unrecognized
                // commands like "once" produce COMMAND_TEXT('o') followed by
                // COMMAND_TEXT('nce...') in CommandTextMode.
                let mut peeked_tokens = Vec::new();
                let mut full_text = String::new();
                loop {
                    let next = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());
                    if next.token_type == yarnspinnerlexer::COMMAND_TEXT {
                        full_text.push_str(next.get_text());
                        peeked_tokens.push(next);
                    } else if next.token_type == yarnspinnerlexer::COMMAND_ONCE {
                        // v3 lexer emits COMMAND_ONCE for the "once" keyword.
                        // Collect it as the text "once" so the synthesis logic fires.
                        full_text.push_str("once");
                        peeked_tokens.push(next);
                    } else if next.token_type == yarnspinnerlexer::COMMAND_ENDONCE {
                        // v3 lexer emits COMMAND_ENDONCE for the "endonce" keyword.
                        // Collect it as the text "endonce" so the synthesis logic fires.
                        full_text.push_str("endonce");
                        peeked_tokens.push(next);
                    } else if next.channel != TOKEN_DEFAULT_CHANNEL {
                        // Hidden-channel token (e.g., EXPR_WS whitespace emitted by
                        // ExpressionMode after COMMAND_ONCE in "<<once if expr>>").
                        // Keep it for potential restoration but continue scanning.
                        peeked_tokens.push(next);
                    } else {
                        peeked_tokens.push(next);
                        break;
                    }
                }
                let trimmed = full_text.trim();
                if trimmed == "endonce" {
                    let was_once_if = self.once_if_block;
                    self.in_once_block = false;
                    self.once_if_block = false;
                    // Consume the closing >> (COMMAND_END or COMMAND_TEXT_END).
                    let last = peeked_tokens.pop().unwrap();
                    if last.token_type != yarnspinnerlexer::COMMAND_TEXT_END && last.token_type != yarnspinnerlexer::COMMAND_END {
                        self.peeked_base_token = Some(last);
                        self.suppress_next_command_text_end = true;
                    }
                    // Synthesize <<endif>> (one for bare once, two for once-if):
                    self.pending_tokens.enqueue(current.clone());
                    self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_ENDIF, "endif"));
                    self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                    if was_once_if {
                        self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_START, "<<"));
                        self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_ENDIF, "endif"));
                        self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                    }
                } else if trimmed == "once" || trimmed.starts_with("once ") {
                    // Consume the closing >> (last peeked token).
                    let last = peeked_tokens.pop().unwrap();

                    // In v3, "<<once if expr>>" produces COMMAND_ONCE then either:
                    //   - COMMAND_IF (type 69) when in a when-clause header, or
                    //   - FUNC_ID with text "if" (type 63) when in a body command,
                    //     because EXPRESSION_WHEN_IF has an IsInWhenClause() sempred.
                    // The peek loop breaks at that token, so `last` is the "if" token.
                    // Detect this and collect the full expression as a String.
                    let is_if_token = |tok: &CommonToken| {
                        tok.token_type == yarnspinnerlexer::COMMAND_IF || (tok.token_type == yarnspinnerlexer::FUNC_ID && tok.get_text() == "if")
                    };
                    let (has_if_expr, once_expr_string): (bool, String) = if is_if_token(last.as_ref()) {
                        let mut parts = String::new();
                        loop {
                            let next = self.peeked_base_token.take().unwrap_or_else(|| self.base.next_token());
                            if next.token_type == yarnspinnerlexer::COMMAND_TEXT_END || next.token_type == yarnspinnerlexer::COMMAND_END {
                                break;
                            }
                            parts.push_str(next.get_text());
                        }
                        (true, parts)
                    } else {
                        if last.token_type != yarnspinnerlexer::COMMAND_TEXT_END && last.token_type != yarnspinnerlexer::COMMAND_END {
                            self.peeked_base_token = Some(last);
                            self.suppress_next_command_text_end = true;
                        }
                        // Determine if there's an expression after "once" from full_text.
                        let after_once = if trimmed == "once" { "" } else { trimmed["once ".len()..].trim() };
                        if let Some(rest) = after_once.strip_prefix("if ") {
                            (true, rest.trim().to_owned())
                        } else {
                            (false, String::new())
                        }
                    };
                    let expr_text: &str = &once_expr_string;

                    if !has_if_expr || expr_text.is_empty() {
                        // Bare <<once>> (no expression)
                        if self.has_text_on_current_line {
                            // Line-level: synthesize <<if true>>
                            self.line_group_metadata.borrow_mut().once_lines.insert(current.get_start());
                            self.pending_tokens.enqueue(current.clone());
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_IF, "if"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::KEYWORD_TRUE, "true"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                        } else {
                            // Block-level: synthesize <<if not $var>><<set $var to true>>
                            self.in_once_block = true;
                            let var_name = self.generate_once_block_variable();
                            self.pending_tokens.enqueue(current.clone());
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_IF, "if"));
                            self.pending_tokens
                                .enqueue(create_common_token(yarnspinnerlexer::OPERATOR_LOGICAL_NOT, "!"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::VAR_ID, &var_name));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                            // Synthesize <<set $var to true>>
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_START, "<<"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_SET, "set"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::VAR_ID, &var_name));
                            self.pending_tokens
                                .enqueue(create_common_token(yarnspinnerlexer::OPERATOR_ASSIGNMENT, "to"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::KEYWORD_TRUE, "true"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                        }
                    } else {
                        // <<once if expr>> — once with an expression
                        let expr_tokens = Self::tokenize_expression(expr_text);

                        if self.has_text_on_current_line {
                            // Line-level: synthesize <<if expr>>
                            self.line_group_metadata.borrow_mut().once_if_lines.insert(current.get_start());
                            self.pending_tokens.enqueue(current.clone());
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_IF, "if"));
                            for tok in expr_tokens {
                                self.pending_tokens.enqueue(Box::new(tok));
                            }
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                        } else {
                            // Block-level: synthesize nested ifs:
                            //   <<if not $var>><<if expr>><<set $var to true>>
                            // The <<endonce>> handler emits two <<endif>> tokens.
                            self.in_once_block = true;
                            self.once_if_block = true;
                            let var_name = self.generate_once_block_variable();
                            // Outer: <<if not $var>>
                            self.pending_tokens.enqueue(current.clone());
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_IF, "if"));
                            self.pending_tokens
                                .enqueue(create_common_token(yarnspinnerlexer::OPERATOR_LOGICAL_NOT, "not"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::VAR_ID, &var_name));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                            // Inner: <<if expr>>
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_START, "<<"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_IF, "if"));
                            for tok in expr_tokens {
                                self.pending_tokens.enqueue(Box::new(tok));
                            }
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                            // Set: <<set $var to true>>
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_START, "<<"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_SET, "set"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::VAR_ID, &var_name));
                            self.pending_tokens
                                .enqueue(create_common_token(yarnspinnerlexer::OPERATOR_ASSIGNMENT, "to"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::KEYWORD_TRUE, "true"));
                            self.pending_tokens.enqueue(create_common_token(yarnspinnerlexer::COMMAND_END, ">>"));
                        }
                    }
                } else {
                    // Not once/endonce — restore peeked tokens and enqueue normally.
                    let mut iter = peeked_tokens.into_iter().rev();
                    if let Some(last) = iter.next() {
                        self.peeked_base_token = Some(last);
                    }
                    let remaining: Vec<_> = iter.rev().collect();
                    self.pending_tokens.enqueue(current.clone());
                    for tok in remaining {
                        self.pending_tokens.enqueue(tok);
                    }
                }
            }
            yarnspinnerlexer::COMMAND_TEXT => {
                self.diagnose_newlines_in_commands(&current);
                self.pending_tokens.enqueue(current.clone());
            }
            yarnspinnerlexer::COMMAND_TEXT_END if self.suppress_next_command_text_end => {
                // Suppress the COMMAND_TEXT_END after a suppressed once/endonce.
                self.suppress_next_command_text_end = false;
            }
            yarnspinnerlexer::BODY_END => {
                self.has_text_on_current_line = false;
                self.line_contains_shortcut = false;
                self.last_indent = 0;
                self.unbalanced_indents.0.clear();
                self.last_seen_option_content = None;
                self.in_once_block = false;
                // [sic from the original!] TODO: this should be empty by now actually...
                self.pending_tokens.enqueue(current.clone());
            }
            _ => {
                // Track whether text has appeared on the current line.
                if current.token_type == yarnspinnerlexer::TEXT {
                    self.has_text_on_current_line = true;
                }
                self.pending_tokens.enqueue(current.clone());
            }
        }

        // Drain any expression tokens deferred by maybe_coalesce_keyword_prefix
        // (set when a COMMAND_IF with no DOT was consumed speculatively and must
        // be emitted immediately after the COMMAND_IF token).
        for tok in std::mem::take(&mut self.deferred_tokens) {
            self.pending_tokens.enqueue(tok);
        }

        // TODO: but... really?
        self.last_token = Some(current);
    }

    fn handle_newline_token(&mut self, current_token: Box<antlr4rust::token::GenericToken<std::borrow::Cow<'input, str>>>) {
        // We're about to go to a new line. Look ahead to see how indented it is.

        // insert the current NEWLINE token
        self.pending_tokens.enqueue(current_token.clone());

        if let Some(last_seen_option_content) = self.last_seen_option_content {
            // [sic!] we are a blank line
            if self
                .last_token
                .as_ref()
                .map(|last| current_token.token_type == last.token_type)
                .unwrap_or_default()
            {
                // is the option content directly above us?
                if self.base.get_line() - last_seen_option_content == 1 {
                    // [sic! (the whole thing)]
                    // so that we don't end up printing <ending option group> into the stream we set the text to be empty
                    // I dislike this and need to look into if you can set a debug text setting in ANTLR
                    // TODO: see above comment
                    // this.InsertToken("<ending option group>", YarnSpinnerLexer.BLANK_LINE_FOLLOWING_OPTION);
                    self.insert_token("", yarnspinnerlexer::BLANK_LINE_FOLLOWING_OPTION);
                }
                // disabling the option tracking
                self.last_seen_option_content = None;
            }
        }

        let current_indentation_length = self.get_length_of_newline_token(&current_token);

        // we need to actually see if there is a shortcut *somewhere* above us
        // if there isn't we just chug on without worrying
        if self.line_contains_shortcut {
            // we have a shortcut *somewhere* above us
            // that means we need to check our depth
            // and compare it to the shortcut depth

            // if the depth of the current line is greater than the previous one
            // we need to add this depth to the indents stack
            if current_indentation_length > self.last_indent {
                self.unbalanced_indents.push(current_indentation_length);
                // [sic!] so that we don't end up printing <indent to 8> into the stream we set the text to be empty
                // I dislike this and need to look into if you can set a debug text setting in ANTLR
                // TODO: see above comment
                // this.InsertToken($"<indent to {currentIndentationLength}>", YarnSpinnerLexer.INDENT);
                self.insert_token("", yarnspinnerlexer::INDENT);
            }

            // we've now started tracking the indentation, or ignored it, so can turn this off
            self.line_contains_shortcut = false;
            self.last_seen_option_content = Some(self.base.get_line());
        }

        // now we need to see if the current depth requires any indents or dedents
        // we do this by first checking to see if there are any unbalanced indents
        if let Some(&initial_top) = self.unbalanced_indents.peek() {
            // [sic!] later should make it check if indentation has changed inside the statement block and throw out a warning
            // this.warnings.Add(new Warning { Token = currentToken, Message = "Indentation inside of shortcut block has changed. This is generally a bad idea."});

            // while there are unbalanced indents
            // we need to check if the current line is shallower than the indent stack
            // if it is then we emit a dedent and continue checking

            let mut top = initial_top;

            while current_indentation_length < top {
                // so that we don't end up printing <indent from 8> into the stream we set the text to be empty
                // I dislike this and need to look into if you can set a debug text setting in ANTLR
                // TODO: see above comment
                // this.InsertToken($"<dedent from {top}>", YarnSpinnerLexer.DEDENT);
                self.insert_token("", yarnspinnerlexer::DEDENT);

                self.unbalanced_indents.pop();

                top = if let Some(&next) = self.unbalanced_indents.peek() {
                    next
                } else {
                    // we've dedented all the way out of the shortcut
                    // as such we are done with the option block
                    // previousLineWasOptionOrOptionBlock = false;
                    self.last_seen_option_content = Some(self.base.get_line());
                    0
                };
            }
        }

        // finally we update the last seen depth
        self.last_indent = current_indentation_length;
    }

    fn handle_eof_token(&mut self, current_token: Box<antlr4rust::token::GenericToken<std::borrow::Cow<'input, str>>>) {
        // We're at the end of the file. Emit as many dedents as we currently have on the stack.
        while let Some(_indent) = self.unbalanced_indents.pop() {
            // so that we don't end up printing <dedent from 8> into the stream we set the text to be empty
            // I dislike this and need to look into if you can set a debug text setting in ANTLR
            // TODO: see above comment
            // this.InsertToken($"<dedent: {indent}>", YarnSpinnerLexer.DEDENT);
            self.insert_token("", yarnspinnerlexer::DEDENT);
        }

        // Finally, enqueue the EOF token.
        self.pending_tokens.enqueue(current_token);
    }

    /// Given a NEWLINE token, return the length of the indentation
    /// following it by counting the spaces and tabs after it.
    fn get_length_of_newline_token(&mut self, current_token: &antlr4rust::token::GenericToken<std::borrow::Cow<'input, str>>) -> isize {
        if current_token.token_type != yarnspinnerlexer::NEWLINE {
            panic!("Current token must NOT be newline")
        }

        let mut length = 0;
        let mut saw_spaces = false;
        let mut saw_tabs = false;

        for c in current_token.get_text().chars() {
            match c {
                ' ' => {
                    length += 1;
                    saw_spaces = true;
                }
                '\t' => {
                    length += 8; // Ye, really (see reference implementation)
                    saw_tabs = true;
                }
                _ => {}
            }
        }

        if saw_spaces && saw_tabs {
            self.diagnostics.borrow_mut().push(
                Diagnostic::from_message("Indentation contains tabs and spaces")
                    .with_range(get_newline_indentation_range(current_token))
                    .with_context(get_newline_indentation_text(current_token))
                    .with_start_line(current_token.line as usize)
                    .with_file_name(self.file_name.clone())
                    .with_severity(DiagnosticSeverity::Warning),
            );
        }

        length
    }

    /// Inserts a new token with the given text and type, as though it
    /// had appeared in the input stream.
    fn insert_token(&mut self, text: impl Into<String>, token_type: i32) {
        // https://www.antlr.org/api/Java/org/antlr/v4/runtime/Lexer.html#_tokenStartCharIndex
        let start_index = self.base.token_start_char_index + self.base.get_text().len() as isize;

        let line = self.get_line();
        let char_position_in_line = self.get_char_position_in_line();

        let token = CommonTokenFactory.create(
            self.base.input.as_mut(),
            token_type,
            Some(text.into()),
            TOKEN_DEFAULT_CHANNEL,
            start_index,
            start_index - 1,
            line,
            char_position_in_line,
        );

        self.pending_tokens.enqueue(token);
    }

    /// Generate a unique variable name for a block-level `<<once>>` statement.
    /// Uses CRC32 of a description string containing the file name and line
    /// number, similar to the C# implementation's approach.
    fn generate_once_block_variable(&self) -> String {
        let description = format!("'once' statement in file {}, line {}", self.file_name, self.base.get_line());
        let hash = crc32fast::hash(description.as_bytes());
        format!("$Yarn.Internal.Once.{hash}")
    }

    /// Tokenize a simple YarnSpinner expression string into ANTLR tokens.
    /// Handles variables, booleans, operators, numbers, parens, and strings.
    fn tokenize_expression(text: &str) -> Vec<CommonToken<'static>> {
        let mut tokens = Vec::new();
        let bytes = text.as_bytes();
        let mut i = 0;
        while i < bytes.len() {
            let c = bytes[i] as char;
            // Skip whitespace
            if c.is_ascii_whitespace() {
                i += 1;
                continue;
            }

            // Variable: $name
            if c == '$' {
                let start = i;
                i += 1;
                while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_' || bytes[i] == b'.') {
                    i += 1;
                }
                tokens.push(*create_common_token(yarnspinnerlexer::VAR_ID, &text[start..i]));
                continue;
            }

            // Two-char operators
            if i + 1 < bytes.len() {
                let two = &text[i..i + 2];
                let tt = match two {
                    "==" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_EQUALS),
                    "!=" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_NOT_EQUALS),
                    ">=" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_GREATER_THAN_EQUALS),
                    "<=" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_LESS_THAN_EQUALS),
                    "&&" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_AND),
                    "||" => Some(yarnspinnerlexer::OPERATOR_LOGICAL_OR),
                    _ => None,
                };
                if let Some(tt) = tt {
                    tokens.push(*create_common_token(tt, two));
                    i += 2;
                    continue;
                }
            }

            // Single-char operators and parens
            let single_tt = match c {
                '!' => Some(yarnspinnerlexer::OPERATOR_LOGICAL_NOT),
                '>' => Some(yarnspinnerlexer::OPERATOR_LOGICAL_GREATER),
                '<' => Some(yarnspinnerlexer::OPERATOR_LOGICAL_LESS),
                '+' => Some(yarnspinnerlexer::OPERATOR_MATHS_ADDITION),
                '-' => Some(yarnspinnerlexer::OPERATOR_MATHS_SUBTRACTION),
                '*' => Some(yarnspinnerlexer::OPERATOR_MATHS_MULTIPLICATION),
                '/' => Some(yarnspinnerlexer::OPERATOR_MATHS_DIVISION),
                '%' => Some(yarnspinnerlexer::OPERATOR_MATHS_MODULUS),
                '(' => Some(yarnspinnerlexer::LPAREN),
                ')' => Some(yarnspinnerlexer::RPAREN),
                _ => None,
            };
            if let Some(tt) = single_tt {
                tokens.push(*create_common_token(tt, &text[i..i + 1]));
                i += 1;
                continue;
            }

            // Number (int or float)
            if c.is_ascii_digit() {
                let start = i;
                while i < bytes.len() && bytes[i].is_ascii_digit() {
                    i += 1;
                }
                if i < bytes.len() && bytes[i] == b'.' {
                    i += 1;
                    while i < bytes.len() && bytes[i].is_ascii_digit() {
                        i += 1;
                    }
                }
                tokens.push(*create_common_token(yarnspinnerlexer::NUMBER, &text[start..i]));
                continue;
            }

            // String literal
            if c == '"' {
                let start = i;
                i += 1;
                while i < bytes.len() && bytes[i] != b'"' {
                    if bytes[i] == b'\\' {
                        i += 1;
                    } // skip escaped char
                    i += 1;
                }
                if i < bytes.len() {
                    i += 1;
                } // closing quote
                tokens.push(*create_common_token(yarnspinnerlexer::STRING, &text[start..i]));
                continue;
            }

            // Word token: keyword or identifier
            if c.is_ascii_alphabetic() || c == '_' {
                let start = i;
                while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                    i += 1;
                }
                let word = &text[start..i];
                let tt = match word {
                    "true" => yarnspinnerlexer::KEYWORD_TRUE,
                    "false" => yarnspinnerlexer::KEYWORD_FALSE,
                    "not" => yarnspinnerlexer::OPERATOR_LOGICAL_NOT,
                    "and" => yarnspinnerlexer::OPERATOR_LOGICAL_AND,
                    "or" => yarnspinnerlexer::OPERATOR_LOGICAL_OR,
                    "xor" => yarnspinnerlexer::OPERATOR_LOGICAL_XOR,
                    "is" => yarnspinnerlexer::OPERATOR_LOGICAL_EQUALS,
                    "neq" => yarnspinnerlexer::OPERATOR_LOGICAL_NOT_EQUALS,
                    "eq" => yarnspinnerlexer::OPERATOR_LOGICAL_EQUALS,
                    "gt" => yarnspinnerlexer::OPERATOR_LOGICAL_GREATER,
                    "gte" => yarnspinnerlexer::OPERATOR_LOGICAL_GREATER_THAN_EQUALS,
                    "lt" => yarnspinnerlexer::OPERATOR_LOGICAL_LESS,
                    "lte" => yarnspinnerlexer::OPERATOR_LOGICAL_LESS_THAN_EQUALS,
                    "null" => yarnspinnerlexer::KEYWORD_NULL,
                    _ => yarnspinnerlexer::FUNC_ID,
                };
                tokens.push(*create_common_token(tt, word));
                continue;
            }

            // Unknown char — skip
            i += 1;
        }
        tokens
    }

    fn diagnose_newlines_in_commands(&mut self, token: &CommonToken<'input>) {
        if token.get_text().contains('\n') {
            let line_len = token.get_text().lines().count();
            let last_line_len = token.get_text().lines().last().unwrap().len();
            self.diagnostics.borrow_mut().push(
                Diagnostic::from_message("Newlines are not allowed in commands")
                    .with_range(
                        Position {
                            line: token.get_line_as_usize() - 1,
                            character: token.get_column_as_usize(),
                        }..Position {
                            line: token.get_line_as_usize() - 1 + line_len,
                            character: last_line_len,
                        },
                    )
                    .with_context(token.get_text().to_string())
                    .with_start_line(token.get_line_as_usize() - 1)
                    .with_file_name(self.file_name.clone())
                    .with_severity(DiagnosticSeverity::Error),
            );
        }
    }
}

fn get_newline_indentation_range(token: &CommonToken<'_>) -> Range<Position> {
    // +1 compared to similar code because we don't want to start at the newline
    let line = token.get_line_as_usize();

    let start = Position { line, character: 0 };
    let stop = Position {
        line,
        character: token.get_text().len(),
    };

    start..stop
}

fn get_newline_indentation_text(token: &CommonToken<'_>) -> String {
    // Skip newline
    token.get_text().chars().skip(1).collect()
}

#[cfg(test)]
mod tests {
    //! To check for behaviour of the C# `IndentAwareLexer`, the following code can be added to a test file in the C# reference:
    //!
    //! Whitespace in the raw string literal is important, and not correctly rendered by markdown renderers!
    //!
    //! ```csharp
    //! using Antlr4.Runtime;
    //! using System.Linq;
    //! using Xunit;
    //! using Xunit.Abstractions;
    //! using Yarn.Compiler;
    //!
    //! namespace YarnSpinner.Tests;
    //!
    //! public class IndentAwareLexerTest
    //! {
    //!     private readonly ITestOutputHelper _testOutputHelper;
    //!
    //!     public IndentAwareLexerTest(ITestOutputHelper testOutputHelper)
    //!     {
    //!         _testOutputHelper = testOutputHelper;
    //!     }
    //!
    //!     [Fact]
    //!     public void NewOne()
    //!     {
    //!         const string input = """
    //! title: Start
    //! ---
    //! -> Option 1
    //!     Nice.
    //! -> Option 2
    //!     Nicer
    //!
    //! This is part of the previous option statement due to indentation on the empty line ahead
    //!
    //! And this doesn't, as the indentation is reset beforehand.
    //!
    //! This belongs to the previous statement, for the same reason.
    //!
    //! ===
    //! """;
    //!
    //!         // For the reference without indentation awareness copy the full lexer and change the base class to `Lexer` (of ANTLR)
    //!         var referenceLexer = new YarnSpinnerLexer(CharStreams.fromstring(input));
    //!         var referenceTokens = referenceLexer.GetAllTokens();
    //!         _testOutputHelper.WriteLine("[{0}]", string.Join(",\n", referenceTokens.Select(t => $"\"{YarnSpinnerLexer.DefaultVocabulary.GetSymbolicName(t.Type)}\"")));
    //!     }
    //! }
    //! ```
    use super::*;
    use crate::prelude::generated::yarnspinnerlexer::YarnSpinnerLexer as GeneratedYarnSpinnerLexer;
    use antlr4rust::InputStream;
    use antlr4rust::common_token_stream::CommonTokenStream;
    use antlr4rust::int_stream::IntStream;
    use antlr4rust::token::TOKEN_EOF;

    #[test]
    fn behaves_like_lexer_for_unindented_input() {
        const MINIMAL_INPUT: &str = "title: Minimal Yarn
---
This is the one and only line
===";

        let generated_lexer = GeneratedYarnSpinnerLexer::new(InputStream::new(MINIMAL_INPUT));
        let indent_aware_lexer = IndentAwareYarnSpinnerLexer::new(InputStream::new(MINIMAL_INPUT), "input.yarn".to_owned());

        let mut reference_token_stream = CommonTokenStream::new(generated_lexer);
        let mut indent_aware_token_stream = CommonTokenStream::new(indent_aware_lexer);

        assert_eq!(reference_token_stream.size(), indent_aware_token_stream.size());

        // Sanity check: Make sure at least one token is read: We do have input.
        assert_eq!(reference_token_stream.iter().next(), indent_aware_token_stream.iter().next());

        // Can not do this, as trying to read EOF panics...
        // Iterator::eq(
        //     reference_token_stream.iter(),
        //     indent_aware_token_stream.iter(),
        // );

        while reference_token_stream.la(1) != TOKEN_EOF {
            assert_eq!(reference_token_stream.iter().next(), indent_aware_token_stream.iter().next());
        }

        assert_eq!(TOKEN_EOF, reference_token_stream.la(1));
        assert_eq!(TOKEN_EOF, indent_aware_token_stream.la(1));
    }

    #[test]
    fn correctly_indents_and_dedents_with_token() {
        let option_indentation_relevant_input: &str = include_str!("significant_whitespace.yarn");

        let indent_aware_lexer = IndentAwareYarnSpinnerLexer::new(InputStream::new(option_indentation_relevant_input), "input.yarn".to_owned());

        let mut indent_aware_token_stream = CommonTokenStream::new(indent_aware_lexer);

        let mut tokens = vec![indent_aware_token_stream.iter().next().unwrap()];

        while indent_aware_token_stream.la(1) != TOKEN_EOF {
            tokens.push(indent_aware_token_stream.iter().next().unwrap());
        }

        let symbols: Vec<_> = tokens
            .into_iter()
            .map(|t| yarnspinnerlexer::_SYMBOLIC_NAMES[t as usize].unwrap())
            .collect();

        // Tests the stability of the lexer, targeted at indents and dedents - might break due to internal changes!
        // See generated_lexer_output_is_same_as_reference for the commented out lines :)
        // TODO: investigate if we can do anything. Maybe fix the rust antlr generator?
        let expected = vec![
            "ID",
            "HEADER_DELIMITER",
            "REST_OF_LINE",
            // "NEWLINE",
            "BODY_START",
            // "NEWLINE",
            "SHORTCUT_ARROW",
            // "BODY_WS",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "INDENT",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "DEDENT",
            "SHORTCUT_ARROW",
            // "BODY_WS",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "INDENT",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "DEDENT",
            // "NEWLINE",
            "BLANK_LINE_FOLLOWING_OPTION",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "BODY_END",
        ];

        assert_eq!(expected, symbols);
    }

    #[test]
    fn generated_lexer_output_is_same_as_reference() {
        let option_indentation_relevant_input: &str = include_str!("significant_whitespace.yarn");

        let generated_lexer = GeneratedYarnSpinnerLexer::new(InputStream::new(option_indentation_relevant_input));
        let mut reference_token_stream = CommonTokenStream::new(generated_lexer);

        let mut tokens = vec![reference_token_stream.iter().next().unwrap()];

        while reference_token_stream.la(1) != TOKEN_EOF {
            tokens.push(reference_token_stream.iter().next().unwrap());
        }

        let symbols: Vec<_> = tokens
            .into_iter()
            .map(|t| yarnspinnerlexer::_SYMBOLIC_NAMES[t as usize].unwrap())
            .collect();

        // Tests the compatibility of the generated lexer with a manually generated output from the reference implementation.
        // The commented out lines are not correctly lexed by the generated lexer (in comparison with the C# generated lexer).
        let expected = vec![
            "ID",
            "HEADER_DELIMITER",
            "REST_OF_LINE",
            // "NEWLINE",
            "BODY_START",
            // "NEWLINE",
            "SHORTCUT_ARROW",
            // "BODY_WS",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "SHORTCUT_ARROW",
            // "BODY_WS",
            "TEXT",
            "TEXT",
            "NEWLINE",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "TEXT",
            "TEXT",
            // "NEWLINE",
            "NEWLINE",
            "BODY_END",
        ];

        assert_eq!(expected, symbols);
    }
}

/// Converts a 0-based character offset in `source` to a `Position` with
/// 0-based `line` and `character` fields.
pub(crate) fn char_offset_to_position(source: &str, char_offset: usize) -> Position {
    let mut line = 0usize;
    let mut col = 0usize;
    for (i, ch) in source.chars().enumerate() {
        if i >= char_offset {
            break;
        }
        if ch == '\n' {
            line += 1;
            col = 0;
        } else {
            col += 1;
        }
    }
    Position { line, character: col }
}
