//! Adapted from <https://github.com/YarnSpinnerTool/YarnSpinner/blob/3a5b7343f715e4e9a3705fa4224e7fa510b92f1c/YarnSpinner.Compiler/DebugInfo.cs>

use crate::prelude::*;
use std::collections::HashMap;
use std::ops::Range;

/// Contains debugging information for all nodes in a compiled Yarn project.
///
/// This is the Rust counterpart of C#'s `ProjectDebugInfo` class.
/// C# exposes this as `CompilationResult.ProjectDebugInfo`; in Rust it is
/// accessed via [`Compilation::debug_info`].
///
/// Unlike C#'s `[Obsolete]` flat `DebugInfo` dictionary (which used O(1)
/// `Dictionary<string, NodeDebugInfo>` lookup), C# migrated to this wrapper
/// holding a `List<NodeDebugInfo>` with a linear-scan `GetNodeDebugInfo()`
/// helper. Rust follows the same shape (Vec + linear scan) for API parity
/// even though `HashMap` would be faster.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "bevy", derive(Reflect))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "bevy", reflect(Debug, PartialEq, Default))]
#[cfg_attr(all(feature = "bevy", feature = "serde"), reflect(Serialize, Deserialize))]
pub struct ProjectDebugInfo {
    /// The debugging info for all nodes in the project.
    pub nodes: Vec<DebugInfo>,
}

impl ProjectDebugInfo {
    /// Returns the [`DebugInfo`] for the node named `node_name`, or `None`
    /// if no such node is present.
    ///
    /// This is the counterpart of C#'s `ProjectDebugInfo.GetNodeDebugInfo(string)`.
    pub fn get_node_debug_info(&self, node_name: &str) -> Option<&DebugInfo> {
        self.nodes.iter().find(|n| n.node_name == node_name)
    }
}

/// Contains debug information for a node in a Yarn file.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "bevy", derive(Reflect))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "bevy", reflect(Debug, PartialEq, Default))]
#[cfg_attr(all(feature = "bevy", feature = "serde"), reflect(Serialize, Deserialize))]
pub struct DebugInfo {
    /// The file that this DebugInfo was produced from.
    pub file_name: String,

    /// The node that this DebugInfo was produced from.
    pub node_name: String,

    /// Whether this node was implicitly generated by the compiler
    /// (e.g., a node-group hub dispatching to candidate nodes).
    pub is_implicit: bool,

    /// The source range of the entire node (from the first header through `===`).
    /// `None` for implicitly-generated nodes that have no source representation.
    pub range: Option<Range<Position>>,

    /// The mapping of instruction numbers to source ranges
    /// in the file indicated by `file_name`.
    pub line_ranges: HashMap<usize, Option<Range<Position>>>,
}

impl DebugInfo {
    /// Gets a [`LineInfo`] object that describes the specified instruction
    /// at the index `instruction_number`.
    ///
    /// # Arguments
    ///
    /// * `instruction_number`: The index of the instruction to retrieve
    ///   information for.
    ///
    /// # Returns
    ///
    /// A [`LineInfo`] object that describes the position of the instruction.
    ///
    /// # Panics
    ///
    /// Panics if `instruction_number` is greater than the
    /// number of instructions present in the node.
    ///
    /// # See also
    ///
    /// * [`DebugInfo::try_get_line_info`] for the fallible version.
    pub fn get_line_info(&self, instruction_number: usize) -> LineInfo {
        self.try_get_line_info(instruction_number).expect("instruction_number out of range")
    }

    /// Fallible version of [`DebugInfo::get_line_info`].
    pub fn try_get_line_info(&self, instruction_number: usize) -> Option<LineInfo> {
        self.line_ranges.get(&instruction_number).map(|range| LineInfo {
            file_name: self.file_name.clone(),
            node_name: self.node_name.clone(),
            range: range.clone(),
        })
    }
}

/// Contains positional information about an instruction.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "bevy", reflect(Debug, PartialEq, Hash))]
#[cfg_attr(all(feature = "bevy", feature = "serde"), reflect(Serialize, Deserialize))]
pub struct LineInfo {
    /// The file name of the source that this instruction was produced from.
    pub file_name: String,

    /// The node name of the source that this instruction was produced from.
    pub node_name: String,

    /// The zero-indexed source range in `file_name` that contains the
    /// statement or expression that this line was produced from.
    pub range: Option<Range<Position>>,
}
