//! Adapted from the listener part of <https://github.com/YarnSpinnerTool/YarnSpinner/blob/3a5b7343f715e4e9a3705fa4224e7fa510b92f1c/YarnSpinner.Compiler/Compiler.cs>

use crate::prelude::*;
use antlr4rust::parser_rule_context::ParserRuleContext;
use antlr4rust::token::Token;
use antlr4rust::tree::{ParseTree, ParseTreeListener, ParseTreeVisitorCompat};
use std::cell::RefCell;
use std::collections::HashSet;
use std::rc::Rc;
use yarnspinner_core::prelude::*;

mod emit;
use crate::parser::generated::yarnspinnerparser::{
    BodyContext,
    Header_when_expressionContextAttrs,
    HeaderContext,
    NodeContext,
    Title_headerContext,
    Title_headerContextAttrs,
    When_headerContext,
    When_headerContextAttrs,
    YarnSpinnerParserContextType,
};
use crate::prelude::generated::yarnspinnerparser::BodyContextAttrs;
use crate::prelude::generated::yarnspinnerparserlistener::YarnSpinnerParserListener;
use crate::visitors::{CodeGenerationVisitor, KnownTypes};
pub(crate) use emit::*;
use std::collections::VecDeque;
use yarnspinner_core::prelude::OpCode;

pub(crate) struct CompilerListener<'input> {
    pub(crate) debug_infos: Rc<RefCell<Vec<DebugInfo>>>,
    /// The program being generated by the compiler.
    pub(crate) program: Rc<RefCell<Program>>,
    /// the list of nodes we have to ensure we track visitation
    pub(crate) tracking_nodes: Rc<RefCell<HashSet<String>>>,
    /// the list of the names of nodes we have said to skip
    pub(crate) skip_nodes: Rc<RefCell<HashSet<String>>>,
    pub(crate) diagnostics: Rc<RefCell<Vec<Diagnostic>>>,
    pub(crate) types: KnownTypes,
    /// The current node to which instructions are being added.
    pub(crate) current_node: Option<Node>,
    /// The current debug information that describes [`current_node`].
    current_debug_info: DebugInfo,
    /// Whether we are currently parsing the
    /// current node as a 'raw text' node, or as a fully syntactic node.
    is_current_node_raw_text: bool,
    pub(crate) file: FileParseResult<'input>,
    label_count: usize,
    /// Per-title queue of unique node names to use instead of the original `title:` value.
    /// Each entry is consumed in document order as nodes with that title are processed.
    pub(crate) node_name_overrides: std::collections::HashMap<String, VecDeque<String>>,
    /// Names of nodes that were implicitly generated by the compiler (e.g. node-group hubs).
    implicit_node_names: HashSet<String>,
}

impl<'input> CompilerListener<'input> {
    pub(crate) fn new(
        tracking_nodes: HashSet<String>,
        skip_nodes: HashSet<String>,
        types: KnownTypes,
        file: FileParseResult<'input>,
        node_name_overrides: std::collections::HashMap<String, VecDeque<String>>,
        implicit_node_names: HashSet<String>,
    ) -> Self {
        Self {
            file,
            types,
            tracking_nodes: Rc::new(RefCell::new(tracking_nodes)),
            skip_nodes: Rc::new(RefCell::new(skip_nodes)),
            current_node: Default::default(),
            current_debug_info: Default::default(),
            is_current_node_raw_text: Default::default(),
            diagnostics: Default::default(),
            program: Default::default(),
            label_count: Default::default(),
            debug_infos: Default::default(),
            node_name_overrides,
            implicit_node_names,
        }
    }

    /// Generates a unique label name to use in the program.
    ///
    /// ## Difference from C#
    ///
    /// The C# compiler resolves jump targets to direct `int32` instruction offsets at
    /// compile time. This Rust port emits human-readable string labels (e.g.
    /// `"L0skip_line"`, `"L1endif"`) that are stored in the `Node.labels` table and
    /// resolved at runtime via `BTreeMap` lookup. This simplifies compilation (labels
    /// are generated independently of instruction indices) at a small runtime cost.
    ///
    /// ## Params
    /// - `commentary` Any additional text to append to the end of the label.
    pub(crate) fn register_label<'b>(&mut self, commentary: impl Into<Option<&'b str>>) -> String {
        let commentary = commentary.into().unwrap_or_default();
        let label = format!("L{}{}", self.label_count, commentary);
        self.label_count += 1;
        label
    }
}

impl<'input> ParseTreeListener<'input, YarnSpinnerParserContextType> for CompilerListener<'input> {}

impl<'input> YarnSpinnerParserListener<'input> for CompilerListener<'input> {
    fn enter_node(&mut self, _ctx: &NodeContext<'input>) {
        // we have found a new node set up the currentNode var ready to hold it and otherwise continue
        self.current_node = Some(Node::default());
        self.current_debug_info = Default::default();
        self.is_current_node_raw_text = false;
    }

    fn exit_node(&mut self, ctx: &NodeContext<'input>) {
        let name = &self.current_node.as_ref().unwrap().name.clone();
        if name.is_empty() {
            // We don't have a name for this node. We can't emit code for it.
            self.diagnostics.borrow_mut().push(
                Diagnostic::from_message("Nodes must have a title")
                    .with_file_name(self.file.name.clone())
                    .with_parser_context(ctx, self.file.tokens())
                    .with_severity(DiagnosticSeverity::Error)
                    .with_code("YS0051"),
            );
        } else if !self.skip_nodes.borrow().contains(name) {
            if !self.program.borrow().nodes.contains_key(name) {
                self.program.borrow_mut().nodes.insert(name.clone(), self.current_node.clone().unwrap());
            } else {
                // Duplicate node name! We'll have caught this during the
                // declarations pass, so no need to issue an error here.
            }
            self.current_debug_info.node_name.clone_from(name);
            self.current_debug_info.file_name.clone_from(&self.file.name);
            self.current_debug_info.is_implicit = self.implicit_node_names.contains(name.as_str());
            self.current_debug_info.range = Some(
                Position {
                    line: ctx.start().get_line_as_usize().saturating_sub(1),
                    character: ctx.start().get_column_as_usize(),
                }..Position {
                    line: ctx.stop().get_line_as_usize().saturating_sub(1),
                    character: ctx.stop().get_column_as_usize() + ctx.stop().get_text().len(),
                },
            );
            self.debug_infos.borrow_mut().push(self.current_debug_info.clone());
        }

        self.current_node = None;
        self.is_current_node_raw_text = false;
    }

    fn exit_title_header(&mut self, ctx: &Title_headerContext<'input>) {
        let current_node = self.current_node.as_mut().unwrap();
        if let Some(title_token) = ctx.ID() {
            let title = title_token.get_text().trim().to_owned();
            if !current_node.name.is_empty() {
                self.diagnostics.borrow_mut().push(
                    Diagnostic::from_message("Nodes must have a single title header")
                        .with_file_name(self.file.name.clone())
                        .with_parser_context(ctx, self.file.tokens())
                        .with_severity(DiagnosticSeverity::Error)
                        .with_code("YS0052"),
                );
            } else {
                let effective_name = self
                    .node_name_overrides
                    .get_mut(&title)
                    .and_then(|q| q.pop_front())
                    .unwrap_or_else(|| title.clone());
                current_node.name.clone_from(&effective_name);
            }
        }
        let header = Header {
            key: "title".to_owned(),
            value: ctx.ID().map(|t| t.get_text().trim().to_owned()).unwrap_or_default(),
        };
        current_node.headers.push(header);
    }

    fn exit_when_header(&mut self, ctx: &When_headerContext<'input>) {
        let current_node = self.current_node.as_mut().unwrap();
        let value = ctx
            .header_when_expression()
            .as_deref()
            .map(|e| {
                if e.COMMAND_ONCE().is_some() {
                    // Reconstruct "once" or "once if <expr>" with proper spacing.
                    // get_text() would concatenate tokens without spaces ("onceif$var").
                    if e.COMMAND_IF().is_some() {
                        let expr_text = e.expression().as_deref().map(|x| x.get_text()).unwrap_or_default();
                        format!("once if {expr_text}")
                    } else {
                        "once".to_owned()
                    }
                } else {
                    e.get_text()
                }
            })
            .unwrap_or_default();
        let header = Header {
            key: "when".to_owned(),
            value,
        };
        current_node.headers.push(header);
    }

    fn exit_header(&mut self, ctx: &HeaderContext<'input>) {
        // have finished with the header so about to enter the node body
        // and all its statements do the initial setup required before
        // compiling that body statements eg emit a new startlabel
        let header_key = ctx.header_key.as_ref().unwrap().get_text();
        let current_node = self.current_node.as_mut().unwrap();

        // Use the header value if provided, else fall back to the
        // empty string. This means that a header like "foo: \n" will
        // be stored as 'foo', '', consistent with how it was typed.
        // That is, it's not null, because a header was provided, but
        // it was written as an empty line.
        let header_value = ctx
            .header_value
            .as_ref()
            .map(|v| strip_header_comment(v.get_text()).trim().to_owned())
            .unwrap_or_default();
        match header_key {
            "title" => {
                if !current_node.name.is_empty() {
                    // YS0052: a second title header found in this node.
                    self.diagnostics.borrow_mut().push(
                        Diagnostic::from_message("Nodes must have a single title header")
                            .with_file_name(self.file.name.clone())
                            .with_parser_context(ctx, self.file.tokens())
                            .with_severity(DiagnosticSeverity::Error)
                            .with_code("YS0052"),
                    );
                } else {
                    // If this title has a node-group name override, consume the next unique name.
                    let effective_name = self
                        .node_name_overrides
                        .get_mut(&header_value)
                        .and_then(|q| q.pop_front())
                        .unwrap_or_else(|| header_value.clone());
                    // Set the name of the node
                    current_node.name.clone_from(&effective_name);
                }
            }
            "tags" => {
                // Split the list of tags by spaces, and use that
                if !header_value.is_empty() {
                    let tags = header_value.split(' ').map(|s| s.to_owned());
                    current_node.tags.extend(tags);
                }
                if current_node.tags.contains(&"rawText".to_owned()) {
                    // This is a raw text node. Flag it as such for future compilation.
                    self.is_current_node_raw_text = true;
                }
            }
            _ => {}
        }
        let header = Header {
            key: header_key.to_owned(),
            value: header_value,
        };
        current_node.headers.push(header);
    }

    fn enter_body(&mut self, ctx: &BodyContext<'input>) {
        // ok so something in here needs to be a bit different
        // also need to emit tracking code here for when we fall out of a node that needs tracking?
        // or should do I do in inside the codegenvisitor?

        // if it is a regular node
        if !self.is_current_node_raw_text {
            // This is the start of a node that we can jump to. Add a
            // label at this point
            let label = self.register_label(None);
            let current_node = self.current_node.as_mut().unwrap();
            current_node.labels.insert(label, current_node.instructions.len() as i32);
            let track = (self.tracking_nodes.borrow().contains(&current_node.name))
                .then(|| Library::generate_unique_visited_variable_for_node(&current_node.name));

            let mut visitor = CodeGenerationVisitor::new(self, track);
            for statement in ctx.statement_all() {
                visitor.visit(statement.as_ref());
            }
        } else {
            // We are a rawText node. Don't compile it; instead, note the string
            let current_node = self.current_node.as_mut().unwrap();
            current_node.source_text_string_id = get_line_id_for_node_name(&current_node.name).0;
        }
    }

    fn exit_body(&mut self, ctx: &BodyContext<'input>) {
        // this gives us the final increment at the end of the node
        // this is for when we visit and complete a node without a jump
        // theoretically this does mean that there might be redundant increments
        // but I don't think it will matter because a jump always prevents
        // the extra increment being reached
        // a bit inelegant to do it this way but the codegen visitor doesn't exit a node
        // will do for now, shouldn't be hard to refactor this later
        let track = {
            let name = &self.current_node.as_ref().unwrap().name;
            (self.tracking_nodes.borrow().contains(name)).then(|| Library::generate_unique_visited_variable_for_node(name))
        };
        if let Some(track) = track {
            CodeGenerationVisitor::generate_tracking_code(self, track);
        }
        // We have exited the body; emit a 'return' opcode here so that
        // <<detour>> callers can be resumed via the call stack, while
        // an empty call stack (normal top-level execution) ends the dialogue.
        self.emit(Emit::from_op_code(OpCode::Return).with_source({
            let pos = Position {
                line: (ctx.stop().line as usize).saturating_sub(1),
                character: 0,
            };
            pos..pos
        }));
    }
}
